declare module 'lucide-react' {
  import { ComponentType, SVGAttributes } from 'react';
  
  export type LucideIcon = ComponentType<SVGAttributes<SVGSVGElement> & {
    size?: number;
    color?: string;
    strokeWidth?: number;
    absoluteStrokeWidth?: boolean;
  }>;
  
  export const Layout: LucideIcon;
export const LayoutDashboard: LucideIcon;
  export const Layout: LucideIcon;
  export const Users: LucideIcon;
  export const GitBranch: LucideIcon;
  export const MousePointer2: LucideIcon;
  export const Smartphone: LucideIcon;
  export const Palette: LucideIcon;
  export const FileText: LucideIcon;
  export const Zap: LucideIcon;
  export const Shield: LucideIcon;
  export const Layers: LucideIcon;
  export const Code: LucideIcon;
  export const PenTool: LucideIcon;
  export const Monitor: LucideIcon;
  export const Tablet: LucideIcon;
  export const Briefcase: LucideIcon;
  export const Plus: LucideIcon;
  export const Search: LucideIcon;
  export const Filter: LucideIcon;
  export const Edit: LucideIcon;
  export const Trash2: LucideIcon;
  export const Eye: LucideIcon;
  export const EyeOff: LucideIcon;
  export const ExternalLink: LucideIcon;
  export const ChevronLeft: LucideIcon;
  export const ChevronRight: LucideIcon;
  export const MoreVertical: LucideIcon;
  export const Calendar: LucideIcon;
  export const Clock: LucideIcon;
  export const Tag: LucideIcon;
  export const Share2: LucideIcon;
  export const Star: LucideIcon;
  export const Sun: LucideIcon;
  export const Moon: LucideIcon;
  export const Menu: LucideIcon;
  export const X: LucideIcon;
  export const ArrowLeft: LucideIcon;
  export const ArrowRight: LucideIcon;
  export const Github: LucideIcon;
  export const Linkedin: LucideIcon;
  export const Twitter: LucideIcon;
  export const Dribbble: LucideIcon;
  export const Instagram: LucideIcon;
  export const Mail: LucideIcon;
  export const MapPin: LucideIcon;
  export const MousePointer: LucideIcon;
  export const Keyboard: LucideIcon;
  export const Sparkles: LucideIcon;
  export const Heart: LucideIcon;
  export const Award: LucideIcon;
  export const BookOpen: LucideIcon;
  export const CheckCircle: LucideIcon;
  export const Loader2: LucideIcon;
  export const Save: LucideIcon;
  export const Image: LucideIcon;
  export const GripVertical: LucideIcon;
  export const ChevronUp: LucideIcon;
  export const ChevronDown: LucideIcon;
  export const LogOut: LucideIcon;
  export const Settings: LucideIcon;
  export const MessageSquare: LucideIcon;
  export const FolderKanban: LucideIcon;
  export const TrendingUp: LucideIcon;
  export const Briefcase: LucideIcon;
  export const Grid: LucideIcon;
  export const List: LucideIcon;
  export const Send: LucideIcon;
}